/* Side A by Ship Notes. MIT. HTMLAudioElement + CSS, no dependencies. */
(() => {
  const fmt=n=>{n=Number.isFinite(n)?Math.max(0,Math.floor(n)):0;return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`};
  class SideA extends HTMLElement{
    static get observedAttributes(){return ['src','track-title','artist'];}
    constructor(){super();this.attachShadow({mode:'open'});this._audio=new Audio();this._audio.preload='metadata';this._audio.volume=.65;this._angle=0;this._speed=0;this._arm=0;this._sleeve=false;this._raf=0;this._last=0;this._generation=0;
      this.shadowRoot.innerHTML=`<style>
        :host{display:block;width:100%;max-width:640px;color:#ede4d6;font-family:Arial,sans-serif;-webkit-font-smoothing:antialiased}*{box-sizing:border-box}.visual{position:relative;width:100%;aspect-ratio:640/635;overflow:clip}.world{position:absolute;width:640px;height:635px;transform-origin:0 0;perspective:1400px}
        .floor{position:absolute;left:35px;top:575px;width:570px;height:47px;border-radius:50%;background:#0009;filter:blur(21px)}
        .jacket{position:absolute;left:74px;top:33px;width:268px;height:267px;background:linear-gradient(135deg,#f0d5ab,#b88759);border-radius:4px;box-shadow:0 12px 25px #0005;transform:rotate(-8deg);overflow:hidden}
        .jacket:before{content:'';position:absolute;inset:0;background:repeating-linear-gradient(0deg,#32160a09 0px,#32160a09 1px,transparent 1px,transparent 3px)}.jacket span{position:absolute;left:20px;top:18px;font:9px ui-monospace,monospace;letter-spacing:2px;color:#51372b}.jacket .sleeve-title{top:auto;bottom:35px;font:italic 44px/1 Georgia,serif;letter-spacing:-2px}
        .insert{position:absolute;left:87px;top:39px;width:250px;height:253px;background:#d48b53;border-radius:3px;transform:rotate(-8deg);box-shadow:0 10px 20px #0005;overflow:hidden;transition:transform .8s cubic-bezier(.2,.8,.2,1);color:#241f22}
        .insert .orb{position:absolute;width:183px;height:183px;left:34px;top:29px;border-radius:50%;background:repeating-linear-gradient(0deg,transparent 0px,transparent 6px,#30272c 6px,#30272c 12px),radial-gradient(circle at 50% 30%,#f4d896,#de9358);transform:rotate(-28deg)}
        .insert .line{position:absolute;width:280px;height:52px;left:-13px;top:101px;background:#d48b53;transform:rotate(-28deg)}.insert .small{position:absolute;left:18px;right:18px;bottom:18px;font:9px ui-monospace,monospace;letter-spacing:2px;display:flex;justify-content:space-between}
        .sleeve-toggle{position:absolute;left:369px;top:117px;min-width:132px;min-height:44px;border:1px solid #e6c39533;border-radius:25px;background:#211d1a;color:#d8c4ac;font:12px Arial,sans-serif;cursor:pointer;transition:scale .15s,background .2s}.sleeve-toggle:hover{background:#32271d}.sleeve-toggle:active{scale:.96}
        .body{position:absolute;left:25px;top:210px;width:590px;height:389px;border-radius:24px;background:linear-gradient(90deg,#452d20,#805134 8%,#6b442c 45%,#3e281e);box-shadow:inset 0 -2px #c88f5433,0 8px 0 #151211,0 22px 35px #0007}
        .deck{position:absolute;inset:0 0 14px;border-radius:24px 24px 18px 18px;background:repeating-linear-gradient(0deg,#ffffff06 0px,#ffffff06 .7px,transparent .7px,transparent 2px),linear-gradient(135deg,#b8aa92,#8c816e 50%,#a99b80);box-shadow:inset 0 2px 1px #ffeed077,inset 0 -1px #32271866,inset 1px 0 #eedfc633}
        .screw{position:absolute;width:10px;height:10px;background:radial-gradient(circle at 35% 20%,#d2c6ad,#655b4b);border-radius:50%;box-shadow:0 1px 2px #30261c88}.screw:after{content:'';position:absolute;left:2px;right:2px;top:4px;height:1px;background:#473d32;transform:rotate(30deg)}.s1{left:13px;top:14px}.s2{right:13px;top:14px}.s3{left:13px;bottom:16px}.s4{right:13px;bottom:16px}
        .platter{position:absolute;left:22px;top:18px;width:338px;height:338px;border-radius:50%;background:repeating-conic-gradient(#c4b8a2 0deg .8deg,#554f46 1deg 1.8deg,#b0a795 2deg 3deg);box-shadow:0 2px 2px #262019,0 6px 9px #30281c88,inset 0 0 0 5px #bfb5a0}
        .vinyl{position:absolute;inset:9px;border-radius:50%;background:repeating-radial-gradient(circle,#151516 0px,#151516 1px,#272626 1.6px,#111213 2.2px,#252525 2.9px);box-shadow:inset 0 0 0 3px #07090a,inset 0 0 0 5px #3a393599;overflow:hidden}
        .vinyl:before{content:'';position:absolute;inset:0;border-radius:50%;background:conic-gradient(from 8deg,transparent,#dddee922 25deg,transparent 62deg,transparent 160deg,#e5d6ba20 201deg,transparent 231deg);pointer-events:none}
        .record-label{position:absolute;inset:109px;border-radius:50%;background:repeating-linear-gradient(0deg,#613b2709 0px,#613b2709 1px,transparent 1px,transparent 3px),#d1a66a;box-shadow:0 0 0 2px #bd8e55,0 0 0 7px #171918;display:flex;align-items:center;flex-direction:column;color:#433022;padding-top:17px}
        .record-label strong{font:italic 23px Georgia,serif;letter-spacing:-1px}.record-label small{font:6px ui-monospace,monospace;letter-spacing:1.5px;margin-top:4px}.record-label .side{margin-top:19px;font:7px ui-monospace,monospace;letter-spacing:1px}
        .spindle{position:absolute;left:163px;top:163px;width:12px;height:12px;border-radius:50%;background:radial-gradient(circle at 35% 25%,#f3ece0,#b0a694 40%,#393a38 80%);box-shadow:1px 2px 3px #0008;z-index:4}
        .pivot{position:absolute;left:431px;top:29px;width:54px;height:54px;border-radius:50%;background:conic-gradient(#4a453e,#e0d6c4,#6e675d,#ddd2bd,#4a453e);box-shadow:0 4px 4px #42392e99,inset 0 0 0 7px #726b5e,inset 0 0 0 8px #d7cbb4}
        .arm{position:absolute;left:426px;top:21px;width:80px;height:251px;transform-origin:32px 35px;z-index:7;filter:drop-shadow(4px 6px 3px #17131077)}.arm svg{width:100%;height:100%;overflow:visible}
        .rest{position:absolute;left:449px;top:198px;width:28px;height:16px;background:linear-gradient(#d6ccb6,#6a6254);border-radius:4px;box-shadow:0 3px 4px #0005}
        .nameplate{position:absolute;left:380px;top:277px;right:24px;color:#352e24}.nameplate strong{font-size:25px;letter-spacing:6px;font-weight:500}.nameplate span{font:8px ui-monospace,monospace;display:block;margin-top:7px;letter-spacing:2px}
        .speed{position:absolute;left:385px;top:242px;font:9px ui-monospace,monospace;color:#493e2e;letter-spacing:1.5px}.lamp{position:absolute;left:521px;top:246px;width:8px;height:8px;border-radius:50%;background:#735d39;box-shadow:inset 0 1px 2px #201911}
        .meter{position:absolute;left:383px;top:327px;width:154px;height:21px;border-radius:5px;background:#29241c;box-shadow:inset 0 1px 4px #08070499,0 1px #ded0b255;display:flex;gap:4px;align-items:center;padding:0 9px}.meter i{display:block;width:8px;height:6px;border-radius:1px;background:#e9b26a;opacity:.17;box-shadow:0 0 6px #edac4922}
        .meta{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:0 12px 18px}.track-title{font:26px/1.2 Georgia,serif;font-style:italic;letter-spacing:-.6px}.artist{font-size:12px;color:#b5a794;margin-top:6px}.edition{font:10px ui-monospace,monospace;letter-spacing:2px;color:#bda98e;text-align:right}
        .transport{display:flex;align-items:center;gap:17px;margin:0 10px}.play{flex:none;width:58px;height:58px;border-radius:50%;background:linear-gradient(#f2d2a0,#b98851);color:#30251b;border:0;box-shadow:inset 0 1px #ffebc7,0 4px 14px #0006;cursor:pointer;position:relative;transition:scale .15s}.play:active{scale:.96}.play:disabled{opacity:.5;cursor:wait}.play svg{position:absolute;width:23px;height:23px;left:18px;top:18px;transition:opacity .3s,scale .3s,filter .3s}.pause-icon{opacity:0;scale:.25;filter:blur(4px)}.playing .play-icon{opacity:0;scale:.25;filter:blur(4px)}.playing .pause-icon{opacity:1;scale:1;filter:blur(0)}
        .seekbox{flex:1;min-width:0}.time{display:flex;justify-content:space-between;font:10px ui-monospace,monospace;color:#bcaa94;font-variant-numeric:tabular-nums;margin:2px 2px 0}input[type=range]{display:block;appearance:none;-webkit-appearance:none;width:100%;height:44px;margin:0;background:transparent;cursor:pointer;--fill:0%}input[type=range]::-webkit-slider-runnable-track{height:3px;border-radius:4px;background:linear-gradient(to right,#d8ae74 var(--fill),#6a5845 var(--fill))}input[type=range]::-webkit-slider-thumb{appearance:none;width:12px;height:12px;border-radius:50%;margin-top:-4.5px;background:#eed7b0;box-shadow:0 1px 4px #0007}input[type=range]::-moz-range-track{height:3px;border-radius:4px;background:#6a5845}input[type=range]::-moz-range-progress{background:#d8ae74;height:3px}input[type=range]::-moz-range-thumb{width:12px;height:12px;border:0;border-radius:50%;background:#eed7b0}.volume{width:96px;flex:none}.volume label{display:block;font-size:9px;letter-spacing:1.2px;color:#bba98d;margin-bottom:-7px}.status{font-size:11px;color:#bbad99;line-height:1.4;margin:17px 12px 0;min-height:18px}
        button:focus-visible,input:focus-visible{outline:2px solid #f7d797;outline-offset:4px}:host([recording]) *{transition:none!important}
        @media(max-width:450px){.volume{width:65px}.transport{gap:10px}.track-title{font-size:24px}.edition{font-size:9px}.play{width:52px;height:52px}.play svg{left:15px;top:15px}}
        @media(prefers-reduced-motion:reduce){*{transition:none!important}}
      </style><div class="visual"><div class="world"><div class="floor"></div><div class="jacket" aria-hidden="true"><span>SHIP NOTES RECORDINGS</span><span class="sleeve-title">After<br>hours.</span></div><div class="insert" aria-hidden="true"><div class="orb"></div><div class="line"></div><div class="small"><span>SIDE A</span><span>STUDIO / 008</span></div></div><button class="sleeve-toggle" type="button" aria-expanded="false">Sleeve notes ↗</button><div class="body"><div class="deck"><i class="screw s1"></i><i class="screw s2"></i><i class="screw s3"></i><i class="screw s4"></i><div class="platter"><div class="vinyl"><div class="record-label"><strong>After hours</strong><small>SHIP NOTES</small><div class="side">A / 33⅓ RPM</div></div></div><div class="spindle"></div></div><div class="rest"></div><div class="pivot"></div><div class="arm" aria-hidden="true"><svg viewBox="0 0 80 251"><defs><linearGradient id="metal" x1="0" x2="1"><stop stop-color="#5c5c59"/><stop offset=".34" stop-color="#e4e0d5"/><stop offset=".53" stop-color="#b4b1a6"/><stop offset="1" stop-color="#66675f"/></linearGradient></defs><rect x="20" y="7" width="25" height="33" rx="6" fill="url(#metal)"/><path d="M32 34V165Q32 180 21 191L9 204" stroke="#393a36" stroke-width="10" fill="none"/><path d="M32 34V165Q32 180 21 191L9 204" stroke="url(#metal)" stroke-width="7" fill="none"/><circle cx="32" cy="35" r="9" fill="url(#metal)"/><g transform="translate(9 202) rotate(38)"><rect x="-10" y="-3" width="21" height="35" rx="4" fill="#262624"/><rect x="-8" y="21" width="17" height="8" rx="2" fill="#c89d60"/><path d="M0 29V35" stroke="#c4c8c5" stroke-width="2"/><path d="M-5 4V16M1 4V16M6 4V16" stroke="#6a6a63" stroke-width="1.5"/></g></svg></div><div class="speed">33⅓ / STEREO</div><div class="lamp"></div><div class="nameplate"><strong>SIDE / A</strong><span>A MOMENT, ON REPEAT.</span></div><div class="meter" aria-hidden="true">${'<i></i>'.repeat(10)}</div></div></div></div></div><div class="meta"><div><div class="track-title">After hours</div><div class="artist">Ship Notes · original demo</div></div><div class="edition">ANALOG FEEL<br>DIGITAL HEART</div></div><div class="transport"><button class="play" type="button" aria-label="Play" aria-pressed="false"><svg class="play-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3L21 12L6 21Z" fill="currentColor"/></svg><svg class="pause-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 3H10V21H5ZM15 3H20V21H15Z" fill="currentColor"/></svg></button><div class="seekbox"><input class="seek" type="range" min="0" max="24" step=".01" value="0" aria-label="Playback position" disabled><div class="time"><span class="elapsed">0:00</span><span class="duration">0:24</span></div></div><div class="volume"><label for="volume">VOLUME</label><input id="volume" type="range" min="0" max="1" step=".01" value=".65" aria-label="Volume"></div></div><p class="status" role="status" aria-live="polite">Press play. Take a moment.</p>`;
      this.$=s=>this.shadowRoot.querySelector(s);this._bars=[...this.shadowRoot.querySelectorAll('.meter i')];
      this.$('.play').addEventListener('click',()=>this._audio.paused?this.play():this.pause());
      this.$('.sleeve-toggle').addEventListener('click',()=>this.toggleSleeve());
      this.$('.seek').addEventListener('input',e=>this.seek(Number(e.target.value)));
      this.$('#volume').addEventListener('input',e=>{this._audio.volume=Number(e.target.value);this.$('#volume').style.setProperty('--fill',`${this._audio.volume*100}%`)});
      this._audio.addEventListener('loadedmetadata',()=>{const d=this._audio.duration;this.$('.seek').max=Number.isFinite(d)?d:0;this.$('.seek').disabled=!Number.isFinite(d)||d<=0;this.$('.duration').textContent=fmt(d);});
      this._audio.addEventListener('play',()=>{this.$('.status').textContent='Playing';this._sync();this._run();});
      this._audio.addEventListener('pause',()=>{this._sync();this._run();});
      this._audio.addEventListener('ended',()=>{this.$('.status').textContent='End of side A. Play it again.';this._sync();this._run();});
      this._audio.addEventListener('error',()=>{this.$('.status').textContent='Could not load this audio. Check the file URL.';this.$('.seek').disabled=true;this.$('.play').disabled=false;this._sync();});
      this._audio.addEventListener('timeupdate',()=>this._progress());this._audio.addEventListener('seeked',()=>this._progress());
    }
    connectedCallback(){this._observer=new ResizeObserver(()=>this.resize());this._observer.observe(this);this.resize();this._applyMeta();if(!this.hasAttribute('recording')&&this.getAttribute('src'))this.src=this.getAttribute('src');this.$('#volume').style.setProperty('--fill','65%');}
    disconnectedCallback(){this._observer?.disconnect();this._generation++;this._pending=false;this.$('.play').disabled=false;this._audio.pause();cancelAnimationFrame(this._raf);this._raf=0;this._last=0;this._speed=0;this._arm=0;}
    attributeChangedCallback(name,old,value){if(old===value||!this.$)return;if(name==='src'&&this.isConnected&&!this.hasAttribute('recording'))this.src=value;else this._applyMeta();}
    _applyMeta(){this.$('.track-title').textContent=this.getAttribute('track-title')||'After hours';this.$('.artist').textContent=this.getAttribute('artist')||'Ship Notes · original demo';}
    resize(){const scale=this.getBoundingClientRect().width/640;this.$('.world').style.transform=`scale(${scale})`;const small=scale<.75;this.$('.sleeve-toggle').style.minHeight=`${small?44/Math.max(scale,.3):44}px`;this.$('.sleeve-toggle').style.fontSize=`${small?12/Math.max(scale,.3):12}px`;}
    get audio(){return this._audio;}
    set src(value){const url=value?new URL(value,document.baseURI):null;if(url&&!['http:','https:','blob:','file:'].includes(url.protocol))throw new TypeError('Unsupported audio URL');this._generation++;this._pending=false;this._audio.pause();this.$('.play').disabled=false;this.$('.seek').disabled=true;if(!url){this._audio.removeAttribute('src');this._audio.load();return;}this._audio.src=url.href;this._audio.load();this.$('.status').textContent='Press play. Take a moment.';}
    get src(){return this._audio.src;}
    async play(){if(!this.src){this.$('.status').textContent='Add an audio source first.';return;}if(this._pending)return;const generation=++this._generation;this._pending=true;this.$('.play').disabled=true;try{if(this._audio.ended)this._audio.currentTime=0;await this._audio.play();}catch(error){if(generation===this._generation)this.$('.status').textContent='Playback could not start. Try Play again or check the file.';}finally{if(generation===this._generation){this._pending=false;this.$('.play').disabled=false;this._sync();}}}
    pause(){this._audio.pause();this.$('.status').textContent='Paused. Stay a little longer.';}
    seek(seconds){if(Number.isFinite(this._audio.duration)&&Number.isFinite(seconds)){this._audio.currentTime=Math.max(0,Math.min(this._audio.duration,seconds));this._progress();}}
    toggleSleeve(force){this._sleeve=typeof force==='boolean'?force:!this._sleeve;this.$('.sleeve-toggle').setAttribute('aria-expanded',String(this._sleeve));this.$('.insert').style.transform=this._sleeve?'translate(218px,-21px) rotate(7deg)':'rotate(-8deg)';}
    _sync(){const playing=!this._audio.paused&&!this._audio.ended;this.$('.transport').classList.toggle('playing',playing);this.$('.play').setAttribute('aria-label',playing?'Pause':'Play');this.$('.play').setAttribute('aria-pressed',String(playing));}
    _progress(){const time=this._audio.currentTime||0,d=this._audio.duration||24;this.$('.seek').value=time;this.$('.seek').style.setProperty('--fill',`${time/d*100}%`);this.$('.elapsed').textContent=fmt(time);this.$('.seek').setAttribute('aria-valuetext',`${fmt(time)} of ${fmt(d)}`);}
    _run(){if(this.hasAttribute('recording')||this._raf||!this.isConnected)return;this._last=0;const tick=now=>{this._raf=0;const dt=this._last?Math.min(.05,(now-this._last)/1000):0;this._last=now;const target=!this._audio.paused&&!this._audio.ended?1:0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this._speed+=(target-this._speed)*(1-Math.exp(-dt/(target?.44:.65)));this._arm+=(target-this._arm)*(1-Math.exp(-dt/.3));if(!reduced)this._angle+=this._speed*200*dt;this.pose(this._angle,reduced?target:this._arm,this._sleeve?1:0,this._audio.currentTime||0,this._audio.duration||24,reduced?target:this._speed,false);if(target||this._speed>.002||this._arm>.002)this._raf=requestAnimationFrame(tick);else{this._last=0;this.pose(this._angle,0,this._sleeve?1:0,this._audio.currentTime||0,this._audio.duration||24,0,false);}};this._raf=requestAnimationFrame(tick);}
    // Deterministic recording API; never starts audio or timers.
    pose(angle,arm,sleeve,time,duration=24,energy=1,record=true){
      this.$('.vinyl').style.transform=`rotate(${angle}deg)`;
      this.$('.arm').style.transform=`rotate(${arm*(31+time/duration*9)}deg) translateY(${-2*(1-arm)}px)`;
      this.$('.lamp').style.background=energy>.02?'#ffd089':'#735d39';this.$('.lamp').style.boxShadow=`0 0 ${12*energy}px ${4*energy}px #ffb34c55,inset 0 1px 1px #ffedc299`;
      this._bars.forEach((b,i)=>b.style.opacity=.13+Math.max(0,Math.min(1,(6+2*Math.sin(time*3)-i)/2))*energy*.87);
      if(record){this.$('.insert').style.transform=`translate(${218*sleeve}px,${-21*sleeve}px) rotate(${-8+15*sleeve}deg)`;this.$('.sleeve-toggle').setAttribute('aria-expanded',String(sleeve>.5));this.$('.seek').value=time;this.$('.seek').style.setProperty('--fill',`${time/duration*100}%`);this.$('.elapsed').textContent=fmt(time);this.$('.duration').textContent=fmt(duration);this.$('.transport').classList.toggle('playing',energy>.1);this.$('.status').textContent=energy>.1?'After hours · original synthesized demo':'Press play. Take a moment.';}
    }
  }
  if(!customElements.get('side-a-player'))customElements.define('side-a-player',SideA);
})();
